# Generated by Django 4.2.20 on 2025-05-05 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='montant',
            field=models.FloatField(default=0),
        ),
    ]
