# Generated by Django 4.2.20 on 2025-05-05 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coach', '0001_initial'),
        ('user', '0002_reservation_montant'),
    ]

    operations = [
        migrations.AddField(
            model_name='membre',
            name='evenements',
            field=models.ManyToManyField(blank=True, related_name='participants', to='coach.evenement'),
        ),
    ]
