# Generated by Django 4.2.20 on 2025-05-05 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_membre_evenements'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='validee',
            field=models.BooleanField(default=False),
        ),
    ]
