# Generated by Django 4.2.20 on 2025-05-05 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_reservation_validee'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='annulee',
            field=models.BooleanField(default=False),
        ),
    ]
