# Generated by Django 4.2.20 on 2025-05-05 22:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('adminclub', '0002_terrain_prix'),
        ('user', '0007_paiement_reservation'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='terrain',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='adminclub.terrain'),
        ),
    ]
