# Generated by Django 4.2.20 on 2025-05-06 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coach', '0006_alter_evenement_lieu_alter_evenement_titre_and_more'),
        ('user', '0008_reservation_terrain'),
    ]

    operations = [
        migrations.AlterField(
            model_name='membre',
            name='evenements',
            field=models.ManyToManyField(blank=True, related_name='membres_inscrits', to='coach.evenement'),
        ),
    ]
