# Generated by Django 4.2.20 on 2025-05-06 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0009_alter_membre_evenements'),
    ]

    operations = [
        migrations.AddField(
            model_name='paiement',
            name='date_facture',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='paiement',
            name='numero_facture',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='paiement',
            name='date',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='paiement',
            name='statut',
            field=models.CharField(choices=[('en_attente', 'En attente'), ('valide', 'Validé'), ('annule', 'Annulé')], default='en_attente', max_length=50),
        ),
    ]
