# Generated by Django 4.2.20 on 2025-05-09 00:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0010_paiement_date_facture_paiement_numero_facture_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paiement',
            name='statut',
            field=models.CharField(choices=[('en_attente', 'En attente'), ('payé', 'Payé'), ('annule', 'Annulé')], default='en_attente', max_length=50),
        ),
    ]
