# Generated by Django 4.2.20 on 2025-05-05 19:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_membre_evenements'),
        ('coach', '0002_coach_motdepasse'),
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fichier', models.FileField(upload_to='documents/')),
                ('type', models.CharField(choices=[('licence', 'Licence'), ('certificat', 'Certificat')], max_length=50)),
                ('date_envoi', models.DateTimeField(auto_now_add=True)),
                ('membre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='user.membre')),
            ],
        ),
    ]
