# Generated by Django 4.2.20 on 2025-05-05 19:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('coach', '0004_document_destinataire'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='document',
            name='membre',
        ),
    ]
