# Generated by Django 4.2.20 on 2025-05-06 14:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0008_reservation_terrain'),
        ('coach', '0005_remove_document_membre'),
    ]

    operations = [
        migrations.AlterField(
            model_name='evenement',
            name='lieu',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='evenement',
            name='titre',
            field=models.CharField(max_length=100),
        ),
        migrations.CreateModel(
            name='ParticipationEvenement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_inscription', models.DateTimeField(auto_now_add=True)),
                ('statut', models.CharField(choices=[('inscrit', 'Inscrit'), ('present', 'Présent'), ('absent', 'Absent')], default='inscrit', max_length=20)),
                ('evenement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='coach.evenement')),
                ('membre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.membre')),
            ],
            options={
                'unique_together': {('membre', 'evenement')},
            },
        ),
        migrations.CreateModel(
            name='Facture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(max_length=20, unique=True)),
                ('montant', models.DecimalField(decimal_places=2, max_digits=10)),
                ('date_emission', models.DateTimeField(auto_now_add=True)),
                ('date_paiement', models.DateTimeField(blank=True, null=True)),
                ('statut', models.CharField(choices=[('en_attente', 'En attente'), ('payee', 'Payée'), ('annulee', 'Annulée')], default='en_attente', max_length=20)),
                ('evenement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='factures', to='coach.evenement')),
                ('membre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='factures', to='user.membre')),
            ],
        ),
        migrations.AddField(
            model_name='evenement',
            name='participants',
            field=models.ManyToManyField(related_name='evenements_participes', through='coach.ParticipationEvenement', to='user.membre'),
        ),
    ]
