# Generated by Django 4.2.20 on 2025-05-05 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminclub', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='terrain',
            name='prix',
            field=models.FloatField(default=0),
        ),
    ]
