# Generated by Django 4.2.20 on 2025-05-06 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminclub', '0002_terrain_prix'),
    ]

    operations = [
        migrations.AddField(
            model_name='admin',
            name='password',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
    ]
