# Generated by Django 4.2.20 on 2025-05-06 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminclub', '0003_admin_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='admin',
            name='password',
            field=models.CharField(default='admin', max_length=128),
        ),
    ]
